import {
  MerchantProfile,
  Product,
  Customer,
  Opportunity,
  Transaction,
  AgentActivityItem,
  AuditLog
} from '../types';

export const INITIAL_MERCHANTS: MerchantProfile[] = [
  {
    id: 'merchant_sports',
    name: 'UrbanKart',
    storeName: 'UrbanKart Sports & Athletics',
    industry: 'Sports & Athletics',
    currency: 'INR',
    currencySymbol: '₹',
    logoInitial: 'U',
    tagline: 'Performance running footwear and endurance athletics',
    policy: {
      merchantId: 'merchant_sports',
      maxDiscountPercent: 15,
      requireApprovalAboveAmount: 4000,
      minConfidenceForAutonomousAction: 75,
      allowAutonomousCheckoutRecovery: true,
      allowAutonomousCrossSell: true,
      razorpayKeyId: 'rzp_test_sports_9921',
      webhookSecret: 'whsec_sports_live_9921',
      testModeActive: true
    },
    stats: {
      revenueGenerated: 482640,
      revenueGrowthPercent: 18.4,
      aiAttributedRevenue: 126840,
      aiAttributedGrowthPercent: 24.7,
      opportunitiesFound: 27,
      conversionLiftPercent: 14.8,
      averageBasketUplift: 799,
      actionsToday: 42,
      successfulActions: 39,
      awaitingApprovalCount: 1,
      blockedCount: 1,
      currentTask: 'Monitoring athletic footwear clickstream & cart events',
      status: 'ONLINE'
    },
    createdAt: '2026-08-15T10:00:00Z'
  },
  {
    id: 'merchant_fashion',
    name: 'FashionHub',
    storeName: 'FashionHub Studio',
    industry: 'Fashion & Apparel',
    currency: 'INR',
    currencySymbol: '₹',
    logoInitial: 'F',
    tagline: 'Curated ethnic kurtis, contemporary dresses & festive styling',
    policy: {
      merchantId: 'merchant_fashion',
      maxDiscountPercent: 20,
      requireApprovalAboveAmount: 5000,
      minConfidenceForAutonomousAction: 80,
      allowAutonomousCheckoutRecovery: true,
      allowAutonomousCrossSell: true,
      razorpayKeyId: 'rzp_test_fashion_4481',
      webhookSecret: 'whsec_fashion_live_4481',
      testModeActive: true
    },
    stats: {
      revenueGenerated: 318450,
      revenueGrowthPercent: 22.1,
      aiAttributedRevenue: 94200,
      aiAttributedGrowthPercent: 31.4,
      opportunitiesFound: 19,
      conversionLiftPercent: 18.2,
      averageBasketUplift: 499,
      actionsToday: 28,
      successfulActions: 26,
      awaitingApprovalCount: 1,
      blockedCount: 0,
      currentTask: 'Analyzing festive ethnic wear intent & lookbook matches',
      status: 'ONLINE'
    },
    createdAt: '2026-08-20T10:00:00Z'
  },
  {
    id: 'merchant_tech',
    name: 'TechNest',
    storeName: 'TechNest Workspace & Gadgets',
    industry: 'Consumer Electronics & Workspace',
    currency: 'INR',
    currencySymbol: '₹',
    logoInitial: 'T',
    tagline: 'Ergonomic workspace hardware, Kevlar phone cases & accessories',
    policy: {
      merchantId: 'merchant_tech',
      maxDiscountPercent: 10,
      requireApprovalAboveAmount: 10000,
      minConfidenceForAutonomousAction: 85,
      allowAutonomousCheckoutRecovery: true,
      allowAutonomousCrossSell: true,
      razorpayKeyId: 'rzp_test_tech_8819',
      webhookSecret: 'whsec_tech_live_8819',
      testModeActive: true
    },
    stats: {
      revenueGenerated: 624100,
      revenueGrowthPercent: 15.6,
      aiAttributedRevenue: 158900,
      aiAttributedGrowthPercent: 19.8,
      opportunitiesFound: 34,
      conversionLiftPercent: 12.4,
      averageBasketUplift: 1299,
      actionsToday: 35,
      successfulActions: 33,
      awaitingApprovalCount: 2,
      blockedCount: 1,
      currentTask: 'Scanning workstation accessory drop-offs & device protection cross-sells',
      status: 'ONLINE'
    },
    createdAt: '2026-08-25T10:00:00Z'
  }
];

export const INITIAL_MERCHANT_PRODUCTS: Record<string, Product[]> = {
  merchant_sports: [
    {
      id: 'prod_vel_01',
      merchantId: 'merchant_sports',
      name: 'Velocity Runner X',
      price: 6999,
      originalPrice: 8499,
      currency: 'INR',
      availability: true,
      stockCount: 42,
      category: 'Running Shoes',
      subcategory: 'Road Running',
      margin: 45,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Lightweight carbon-infused running shoe engineered for high-cadence daily road training.',
      features: ['Carbon-fiber propulsive plate', 'Micro-mesh upper', 'Nitrogen-infused foam', 'High-abrasion outsole'],
      aiBuyerTags: ['Running', 'Lightweight', 'Road Running', 'Shoes', 'Footwear'],
      suitableFor: ['daily-training', 'long-distance', 'tempo-runs'],
      crossSellAffinity: [
        {
          productId: 'prod_socks_01',
          productName: 'Pro Dynamic Running Socks (3-Pack)',
          affinityScore: 0.94,
          price: 799,
          reason: '78% of Velocity Runner buyers add anti-blister compression socks.'
        }
      ],
      priceElasticityScore: 0.76,
      purchaseEligibility: 'Instant checkout ready in Razorpay Test Mode.',
      jsonLdSchema: { '@type': 'Product', name: 'Velocity Runner X', price: 6999 }
    },
    {
      id: 'prod_swift_02',
      merchantId: 'merchant_sports',
      name: 'SwiftRun Pro Max',
      price: 5999,
      originalPrice: 6999,
      currency: 'INR',
      availability: true,
      stockCount: 18,
      category: 'Running Shoes',
      subcategory: 'Cushioned Running',
      margin: 40,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Ultra-cushioned stability shoe ideal for daily jogging and joint protection.',
      features: ['Extra-wide ergonomic toe box', 'High-rebound EVA sole', 'Reflective accents'],
      aiBuyerTags: ['Running', 'Cushioned', 'Stability', 'Shoes', 'Footwear'],
      suitableFor: ['recovery-runs', 'daily-jogging', 'walking'],
      crossSellAffinity: [
        {
          productId: 'prod_socks_01',
          productName: 'Pro Dynamic Running Socks (3-Pack)',
          affinityScore: 0.88,
          price: 799,
          reason: 'Recommended for arch blister prevention.'
        }
      ],
      priceElasticityScore: 0.81,
      purchaseEligibility: 'Ready for cross-sell recommendation.',
      jsonLdSchema: { '@type': 'Product', name: 'SwiftRun Pro Max', price: 5999 }
    },
    {
      id: 'prod_aero_03',
      merchantId: 'merchant_sports',
      name: 'AeroFlex Marathon Ultra',
      price: 8499,
      originalPrice: 9999,
      currency: 'INR',
      availability: true,
      stockCount: 12,
      category: 'Running Shoes',
      subcategory: 'Competition Racing',
      margin: 48,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Elite race-day shoe with full-length carbon propulsion rocker designed for marathon attempts.',
      features: ['Full curved rigid carbon plate', 'PEBA ultralight foam', '178g featherweight'],
      aiBuyerTags: ['Racing', 'Marathon', 'Carbon-Plate', 'Elite', 'Shoes'],
      suitableFor: ['race-day', 'marathon-pace', 'track-intervals'],
      crossSellAffinity: [
        {
          productId: 'prod_foam_01',
          productName: 'Deep Recovery Foam Roller',
          affinityScore: 0.91,
          price: 1299,
          reason: 'Essential post-race fascial release bundle.'
        }
      ],
      priceElasticityScore: 0.65,
      purchaseEligibility: 'Ready for 1-click Razorpay Test Mode checkout.',
      jsonLdSchema: { '@type': 'Product', name: 'AeroFlex Marathon Ultra', price: 8499 }
    },
    {
      id: 'prod_socks_01',
      merchantId: 'merchant_sports',
      name: 'Pro Dynamic Running Socks (3-Pack)',
      price: 799,
      originalPrice: 999,
      currency: 'INR',
      availability: true,
      stockCount: 150,
      category: 'Accessories & Apparel',
      subcategory: 'Socks',
      margin: 55,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Anti-blister seamless compression socks engineered specifically for endurance runners.',
      features: ['Arch compression band', 'CoolMax fiber', 'Seamless toe box'],
      aiBuyerTags: ['Accessories', 'Socks', 'Anti-Blister', 'Compression'],
      suitableFor: ['daily-training', 'long-distance', 'blister-prevention'],
      crossSellAffinity: [],
      priceElasticityScore: 0.92,
      purchaseEligibility: 'High-affinity bundle add-on.',
      jsonLdSchema: { '@type': 'Product', name: 'Pro Dynamic Running Socks', price: 799 }
    },
    {
      id: 'prod_foam_01',
      merchantId: 'merchant_sports',
      name: 'Deep Recovery Foam Roller',
      price: 1299,
      originalPrice: 1699,
      currency: 'INR',
      availability: true,
      stockCount: 60,
      category: 'Recovery Gear',
      subcategory: 'Mobility',
      margin: 50,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1600881333168-2ef49b341f30?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Grid-textured trigger point muscle massager for IT band and calf tightness relief.',
      features: ['Multi-density grid matrix', 'Hollow core construction', 'Sweat-resistant EVA'],
      aiBuyerTags: ['Recovery', 'Mobility', 'Muscle-Relief', 'Foam Roller'],
      suitableFor: ['post-workout', 'muscle-relief'],
      crossSellAffinity: [],
      priceElasticityScore: 0.85,
      purchaseEligibility: 'Ready for autonomous upsell.',
      jsonLdSchema: { '@type': 'Product', name: 'Deep Recovery Foam Roller', price: 1299 }
    },
    {
      id: 'prod_flask_01',
      merchantId: 'merchant_sports',
      name: 'Hydration Flask 750ml',
      price: 499,
      originalPrice: 699,
      currency: 'INR',
      availability: true,
      stockCount: 95,
      category: 'Accessories & Apparel',
      subcategory: 'Hydration',
      margin: 60,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'BPA-free squeezable ergonomic sports water bottle with leak-proof jet valve.',
      features: ['BPA-free poly', 'High-flow jet valve', 'Ergonomic grip indents'],
      aiBuyerTags: ['Hydration', 'Bottle', 'Accessories', 'Water Bottle'],
      suitableFor: ['running', 'gym', 'cycling'],
      crossSellAffinity: [],
      priceElasticityScore: 0.95,
      purchaseEligibility: 'Ready for checkout cross-sell.',
      jsonLdSchema: { '@type': 'Product', name: 'Hydration Flask 750ml', price: 499 }
    },
    {
      id: 'prod_cap_01',
      merchantId: 'merchant_sports',
      name: 'Breathable Running Cap',
      price: 699,
      originalPrice: 899,
      currency: 'INR',
      availability: true,
      stockCount: 70,
      category: 'Accessories & Apparel',
      subcategory: 'Headwear',
      margin: 52,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'UPF 50+ sun protection ultra-light running hat with moisture-wicking sweatband.',
      features: ['Laser cut ventilation', 'Dark underbill to reduce glare', 'Adjustable clasp'],
      aiBuyerTags: ['Cap', 'Hat', 'Headwear', 'Running Gear'],
      suitableFor: ['outdoor-running', 'trail-running', 'sun-protection'],
      crossSellAffinity: [],
      priceElasticityScore: 0.88,
      purchaseEligibility: 'Ready for cross-sell recommendation.',
      jsonLdSchema: { '@type': 'Product', name: 'Breathable Running Cap', price: 699 }
    }
  ],

  merchant_fashion: [
    {
      id: 'prod_fash_01',
      merchantId: 'merchant_fashion',
      name: 'Urban Performance Kurti',
      price: 899,
      originalPrice: 1299,
      currency: 'INR',
      availability: true,
      stockCount: 48,
      category: 'Ethnic Wear',
      subcategory: 'Kurtis',
      margin: 42,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Pure breathable cotton straight-fit kurti with delicate threadwork, ideal for daily office & casual wear.',
      features: ['100% Breathable cotton', 'Straight silhouette with side slits', 'Round neck with subtle embroidery', 'Colorfast bio-washed fabric'],
      aiBuyerTags: ['Kurti', 'Kurtis', 'Ethnic Wear', 'Women', 'Cotton', 'Under-1k', 'Casual'],
      suitableFor: ['daily-wear', 'office-ethnic', 'casual-outings', 'college'],
      crossSellAffinity: [
        {
          productId: 'prod_fash_04',
          productName: 'Chiffon Matching Dupatta',
          affinityScore: 0.95,
          price: 499,
          reason: '84% of kurti buyers bundle a coordinated lightweight chiffon dupatta.'
        },
        {
          productId: 'prod_fash_03',
          productName: 'Cotton Comfort Palazzo Pants',
          affinityScore: 0.89,
          price: 699,
          reason: 'Complete the ethnic look with matching wide-leg palazzo pants.'
        }
      ],
      priceElasticityScore: 0.88,
      purchaseEligibility: 'Instant checkout ready in Razorpay Test Mode.',
      jsonLdSchema: { '@type': 'Product', name: 'Urban Performance Kurti', price: 899 }
    },
    {
      id: 'prod_fash_02',
      merchantId: 'merchant_fashion',
      name: 'Everyday Casual Floral Dress',
      price: 999,
      originalPrice: 1499,
      currency: 'INR',
      availability: true,
      stockCount: 36,
      category: 'Western Wear',
      subcategory: 'Dresses',
      margin: 45,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'A-line floral print midi dress with elasticated waist and flared hem for effortless summer styling.',
      features: ['Lightweight georgette with soft lining', 'V-neckline with smocked waist', 'Midi length flare', 'Wrinkle-resistant fabric'],
      aiBuyerTags: ['Dress', 'Dresses', 'Western Wear', 'Floral', 'Midi Dress', 'Under-1k', 'Summer'],
      suitableFor: ['brunch', 'summer-outings', 'casual-dates', 'travel'],
      crossSellAffinity: [
        {
          productId: 'prod_fash_06',
          productName: 'Oversized Cotton Linen Shirt',
          affinityScore: 0.78,
          price: 1299,
          reason: 'Frequently layered as an open shrug/jacket over floral dresses.'
        }
      ],
      priceElasticityScore: 0.82,
      purchaseEligibility: 'Ready for 1-click Razorpay Test Mode checkout.',
      jsonLdSchema: { '@type': 'Product', name: 'Everyday Casual Floral Dress', price: 999 }
    },
    {
      id: 'prod_fash_03',
      merchantId: 'merchant_fashion',
      name: 'Cotton Comfort Palazzo Pants',
      price: 699,
      originalPrice: 999,
      currency: 'INR',
      availability: true,
      stockCount: 60,
      category: 'Bottom Wear',
      subcategory: 'Palazzos',
      margin: 38,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Wide-leg relaxed fit pure cotton palazzo with elasticated drawstring waistband.',
      features: ['100% Cambric cotton', 'Deep functional side pockets', 'Full-length wide leg flare'],
      aiBuyerTags: ['Palazzo', 'Bottom Wear', 'Pants', 'Cotton', 'Ethnic'],
      suitableFor: ['daily-comfort', 'kurti-pairing', 'lounging'],
      crossSellAffinity: [],
      priceElasticityScore: 0.90,
      purchaseEligibility: 'Ready for cross-sell add-on.',
      jsonLdSchema: { '@type': 'Product', name: 'Cotton Comfort Palazzo Pants', price: 699 }
    },
    {
      id: 'prod_fash_04',
      merchantId: 'merchant_fashion',
      name: 'Chiffon Matching Dupatta',
      price: 499,
      originalPrice: 699,
      currency: 'INR',
      availability: true,
      stockCount: 80,
      category: 'Ethnic Wear',
      subcategory: 'Dupattas',
      margin: 50,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
      aiSummary: '2.25 meter lightweight chiffon dupatta with delicate golden border lace.',
      features: ['Featherlight sheer chiffon', 'Gold metallic lace border', '2.25m length'],
      aiBuyerTags: ['Dupatta', 'Ethnic', 'Accessories', 'Chiffon', 'Bundle-Addon'],
      suitableFor: ['kurti-styling', 'festive-accents', 'mix-match'],
      crossSellAffinity: [],
      priceElasticityScore: 0.94,
      purchaseEligibility: 'High-affinity 1-click bundle item.',
      jsonLdSchema: { '@type': 'Product', name: 'Chiffon Matching Dupatta', price: 499 }
    },
    {
      id: 'prod_fash_05',
      merchantId: 'merchant_fashion',
      name: 'Embroidered Anarkali Kurta Set',
      price: 1899,
      originalPrice: 2499,
      currency: 'INR',
      availability: true,
      stockCount: 24,
      category: 'Ethnic Wear',
      subcategory: 'Anarkali Sets',
      margin: 44,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1583391733981-645b23d9b546?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Flared royal Anarkali kurta with zari yoke embroidery, matching pants and dupatta.',
      features: ['Flared 32-kali Anarkali cut', 'Intricate zari & sequin work', 'Complete 3-piece set'],
      aiBuyerTags: ['Anarkali', 'Kurti', 'Kurta', 'Festive', 'Party Wear', 'Ethnic Set'],
      suitableFor: ['weddings', 'festivals', 'occasions'],
      crossSellAffinity: [],
      priceElasticityScore: 0.72,
      purchaseEligibility: 'Ready for 1-click checkout.',
      jsonLdSchema: { '@type': 'Product', name: 'Embroidered Anarkali Kurta Set', price: 1899 }
    },
    {
      id: 'prod_fash_06',
      merchantId: 'merchant_fashion',
      name: 'Oversized Cotton Linen Shirt',
      price: 1299,
      originalPrice: 1799,
      currency: 'INR',
      availability: true,
      stockCount: 30,
      category: 'Western Wear',
      subcategory: 'Tops & Shirts',
      margin: 40,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Relaxed drop-shoulder button-down linen shirt for versatile unisex styling.',
      features: ['60% Linen 40% Cotton blend', 'Relaxed boyfriend fit', 'Chest pocket with horn buttons'],
      aiBuyerTags: ['Shirt', 'Tops', 'Linen', 'Casual', 'Western Wear'],
      suitableFor: ['casual-layering', 'work-from-home', 'travel'],
      crossSellAffinity: [],
      priceElasticityScore: 0.80,
      purchaseEligibility: 'Ready for autonomous recommendation.',
      jsonLdSchema: { '@type': 'Product', name: 'Oversized Cotton Linen Shirt', price: 1299 }
    }
  ],

  merchant_tech: [
    {
      id: 'prod_stand_01',
      merchantId: 'merchant_tech',
      name: 'UltraSlim Ergonomic Aluminum Laptop Stand',
      price: 3499,
      originalPrice: 4299,
      currency: 'INR',
      availability: true,
      stockCount: 40,
      category: 'Workstation Accessories',
      subcategory: 'Laptop Stands',
      margin: 35,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'CNC-machined anodized aluminum foldaway laptop riser designed for posture alignment and thermal cooling.',
      features: ['Precision CNC aerospace aluminum', 'Dual-axis stepless height adjustment', 'Ventilated cooling airflow'],
      aiBuyerTags: ['Workstation', 'Laptop Stand', 'Ergonomic', 'Desk Setup', 'Aluminum', 'MacBook'],
      suitableFor: ['home-office', 'ergonomic-posture', 'macbook-setup'],
      crossSellAffinity: [
        {
          productId: 'prod_mouse_01',
          productName: 'SilentClick Dual-Mode Wireless Mouse',
          affinityScore: 0.92,
          price: 1299,
          reason: '86% of laptop stand buyers pair an external ergonomic wireless mouse.'
        }
      ],
      priceElasticityScore: 0.82,
      purchaseEligibility: 'Ready for 1-click Razorpay Test Mode checkout.',
      jsonLdSchema: { '@type': 'Product', name: 'UltraSlim Ergonomic Aluminum Laptop Stand', price: 3499 }
    },
    {
      id: 'prod_case_01',
      merchantId: 'merchant_tech',
      name: 'MagShield Kevlar Phone Case (iPhone 15 Pro)',
      price: 1499,
      originalPrice: 1999,
      currency: 'INR',
      availability: true,
      stockCount: 75,
      category: 'Tech Accessories',
      subcategory: 'Phone Cases',
      margin: 48,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Aerospace-grade 600D Aramid fiber case with embedded high-strength MagSafe magnetic ring array.',
      features: ['Genuine 600D Kevlar weave', 'Ultra-thin 0.85mm profile', 'Military 10ft drop tested', 'N52 MagSafe ring'],
      aiBuyerTags: ['Electronics', 'iPhone 15 Pro', 'Phone Case', 'Phone Cover', 'MagSafe', 'Kevlar'],
      suitableFor: ['daily-protection', 'wireless-charging', 'minimalist-gadgets'],
      crossSellAffinity: [
        {
          productId: 'prod_screen_01',
          productName: '9H DiamondEdge Screen Protector',
          affinityScore: 0.95,
          price: 799,
          reason: '92% of Kevlar case buyers add 9H tempered screen protection.'
        }
      ],
      priceElasticityScore: 0.88,
      purchaseEligibility: 'Ready for 1-click Razorpay Test Mode checkout.',
      jsonLdSchema: { '@type': 'Product', name: 'MagShield Kevlar Phone Case', price: 1499 }
    },
    {
      id: 'prod_screen_01',
      merchantId: 'merchant_tech',
      name: '9H DiamondEdge Screen Protector',
      price: 799,
      originalPrice: 999,
      currency: 'INR',
      availability: true,
      stockCount: 120,
      category: 'Tech Accessories',
      subcategory: 'Screen Protectors',
      margin: 60,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Edge-to-edge shatterproof tempered glass with oleophobic anti-fingerprint coating.',
      features: ['9H hardness scratch-resistant', 'Oleophobic nano-coating', 'TrueTouch sensitivity', 'Alignment tray included'],
      aiBuyerTags: ['Electronics', 'Screen Protector', 'Screen Guard', 'Tempered Glass', 'iPhone 15 Pro'],
      suitableFor: ['screen-protection', 'scratch-resistance'],
      crossSellAffinity: [],
      priceElasticityScore: 0.94,
      purchaseEligibility: 'Instant checkout cross-sell item.',
      jsonLdSchema: { '@type': 'Product', name: '9H DiamondEdge Screen Protector', price: 799 }
    },
    {
      id: 'prod_mouse_01',
      merchantId: 'merchant_tech',
      name: 'SilentClick Dual-Mode Wireless Mouse',
      price: 1299,
      originalPrice: 1799,
      currency: 'INR',
      availability: true,
      stockCount: 55,
      category: 'Workstation Accessories',
      subcategory: 'Peripherals',
      margin: 38,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Ergonomic 2.4GHz + Bluetooth dual-connectivity silent mouse with USB-C fast recharging.',
      features: ['90% noise-reduced silent clicks', 'Dual-mode Bluetooth 5.2 + 2.4GHz USB', 'Up to 90 days battery life'],
      aiBuyerTags: ['Mouse', 'Wireless Mouse', 'Workstation', 'Peripherals', 'Bluetooth'],
      suitableFor: ['office-work', 'laptop-setup', 'travel'],
      crossSellAffinity: [],
      priceElasticityScore: 0.86,
      purchaseEligibility: 'Ready for cross-sell add-on.',
      jsonLdSchema: { '@type': 'Product', name: 'SilentClick Dual-Mode Wireless Mouse', price: 1299 }
    },
    {
      id: 'prod_bag_01',
      merchantId: 'merchant_tech',
      name: 'Water-Resistant Commuter Laptop Bag 15.6"',
      price: 2499,
      originalPrice: 3299,
      currency: 'INR',
      availability: true,
      stockCount: 32,
      category: 'Workstation Accessories',
      subcategory: 'Bags & Sleeves',
      margin: 42,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
      aiSummary: 'Shockproof padded weather-resistant messenger bag with luggage strap and dedicated tablet slot.',
      features: ['High-density foam shock padding', 'Water-repellent Oxford fabric', 'YKK metal zippers'],
      aiBuyerTags: ['Laptop Bag', 'Bags', 'Sleeve', 'Travel', 'Workstation'],
      suitableFor: ['daily-commute', 'business-travel', 'device-protection'],
      crossSellAffinity: [],
      priceElasticityScore: 0.78,
      purchaseEligibility: 'Ready for autonomous recommendation.',
      jsonLdSchema: { '@type': 'Product', name: 'Water-Resistant Commuter Laptop Bag', price: 2499 }
    },
    {
      id: 'prod_hub_01',
      merchantId: 'merchant_tech',
      name: 'ProDesk Multi-Port USB-C Hub 7-in-1',
      price: 2199,
      originalPrice: 2899,
      currency: 'INR',
      availability: true,
      stockCount: 45,
      category: 'Workstation Accessories',
      subcategory: 'Connectivity',
      margin: 40,
      status: 'Active',
      image: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=600&auto=format&fit=crop&q=80',
      aiSummary: '4K HDMI, 100W Power Delivery, SD card reader and 3x USB 3.0 ports in an aircraft aluminum shell.',
      features: ['4K@60Hz HDMI output', '100W USB-C Pass-through charging', 'Aircraft aluminum shell'],
      aiBuyerTags: ['USB-C Hub', 'Dock', 'Adapter', 'Connectivity', 'Workstation'],
      suitableFor: ['macbook-dock', 'laptop-setup', 'multi-monitor'],
      crossSellAffinity: [],
      priceElasticityScore: 0.84,
      purchaseEligibility: 'Ready for 1-click Razorpay Test Mode checkout.',
      jsonLdSchema: { '@type': 'Product', name: 'ProDesk Multi-Port USB-C Hub', price: 2199 }
    }
  ]
};

export const INITIAL_MERCHANT_CUSTOMERS: Record<string, Customer[]> = {
  merchant_sports: [
    {
      id: 'cust_sports_demo',
      merchantId: 'merchant_sports',
      name: 'UrbanKart Shopper',
      email: 'customer@urbankart.demo',
      phone: '+91 98765 43210',
      location: 'Mumbai, MH',
      createdAt: '2026-08-30T10:00:00.000Z',
      lifetimeValue: 18900,
      status: 'high_intent',
      avatarColor: '#111111',
      currentIntent: 'HIGH_PURCHASE_INTENT',
      nextBestAction: 'Explore store catalog with AI Shopping Agent',
      metrics: {
        totalOrders: 0,
        totalSpend: 0,
        averageOrderValue: 0,
        lastPurchaseAt: null
      },
      behavior: {
        viewedTimes: 3,
        lastViewedProduct: 'Velocity Runner X',
        cartValue: 0,
        cartItems: [],
        daysActive: 2,
        hasPurchased: false,
        intentScore: 88,
        preferredCategories: ['Running Shoes', 'Athletics'],
        viewedProducts: ['Velocity Runner X'],
        searchQueries: ['I need running shoes under ₹7,000'],
        cartAdds: [],
        abandonedCarts: [],
        purchases: []
      }
    },
    {
      id: 'cust_sports_102',
      merchantId: 'merchant_sports',
      name: 'Aarav Mehta',
      email: 'aarav.m@example.com',
      phone: '+91 98201 44819',
      location: 'Bengaluru, KA',
      createdAt: '2026-08-28T10:00:00.000Z',
      lifetimeValue: 14500,
      status: 'high_intent',
      avatarColor: '#111111',
      currentIntent: 'HIGH_PURCHASE_INTENT',
      nextBestAction: 'Recommend Pro Dynamic Running Socks as a complementary product',
      metrics: {
        totalOrders: 0,
        totalSpend: 0,
        averageOrderValue: 0,
        lastPurchaseAt: null
      },
      behavior: {
        viewedTimes: 4,
        lastViewedProduct: 'Velocity Runner X',
        cartValue: 6999,
        cartItems: ['Velocity Runner X'],
        daysActive: 3,
        hasPurchased: false,
        intentScore: 94,
        preferredCategories: ['Running Shoes', 'Fitness Gear'],
        viewedProducts: ['Velocity Runner X', 'Pro Dynamic Running Socks'],
        searchQueries: ['I need running shoes under ₹7,000'],
        cartAdds: [
          { productId: 'prod_sports_001', productName: 'Velocity Runner X', price: 6999, timestamp: '10 mins ago', source: 'DIRECT_SEARCH' }
        ],
        abandonedCarts: [],
        purchases: []
      }
    },
    {
      id: 'cust_sports_103',
      merchantId: 'merchant_sports',
      name: 'Ananya Iyer',
      email: 'ananya.i@example.com',
      phone: '+91 99002 88310',
      location: 'Hyderabad, TS',
      createdAt: '2026-08-25T11:20:00.000Z',
      lifetimeValue: 34000,
      status: 'high_intent',
      avatarColor: '#111111',
      currentIntent: 'HIGH_PURCHASE_INTENT',
      nextBestAction: 'Offer Marathon Fuel Pack bundle upgrade',
      metrics: {
        totalOrders: 2,
        totalSpend: 16998,
        averageOrderValue: 8499,
        lastPurchaseAt: '2026-08-20T14:15:00.000Z'
      },
      behavior: {
        viewedTimes: 6,
        lastViewedProduct: 'AeroFlex Marathon Ultra',
        cartValue: 8499,
        cartItems: ['AeroFlex Marathon Ultra'],
        daysActive: 5,
        hasPurchased: true,
        intentScore: 92,
        preferredCategories: ['Running Shoes', 'Apparel'],
        viewedProducts: ['AeroFlex Marathon Ultra', 'AeroGrip Performance Sports Socks'],
        searchQueries: ['Find marathon running shoes'],
        cartAdds: [
          { productId: 'prod_sports_002', productName: 'AeroFlex Marathon Ultra', price: 8499, timestamp: '25 mins ago', source: 'AI_SEARCH' }
        ],
        abandonedCarts: [],
        purchases: [
          { orderId: 'ord_sp_881', amount: 8499, items: ['AeroFlex Marathon Ultra'], timestamp: '2026-08-20T14:15:00.000Z' }
        ]
      }
    },
    {
      id: 'cust_sports_104',
      merchantId: 'merchant_sports',
      name: 'Vikram Sengupta',
      email: 'vikram.s@example.com',
      phone: '+91 98310 11982',
      location: 'Kolkata, WB',
      createdAt: '2026-08-29T16:40:00.000Z',
      lifetimeValue: 18500,
      status: 'active',
      avatarColor: '#555555',
      currentIntent: 'MODERATE_INTEREST',
      nextBestAction: 'Cross-sell hydration accessories',
      metrics: {
        totalOrders: 1,
        totalSpend: 5999,
        averageOrderValue: 5999,
        lastPurchaseAt: '2026-08-29T17:00:00.000Z'
      },
      behavior: {
        viewedTimes: 2,
        lastViewedProduct: 'SwiftRun Pro Max',
        cartValue: 5999,
        cartItems: ['SwiftRun Pro Max'],
        daysActive: 1,
        hasPurchased: true,
        intentScore: 78,
        preferredCategories: ['Running Shoes'],
        viewedProducts: ['SwiftRun Pro Max'],
        searchQueries: ['Shoes for daily training'],
        cartAdds: [
          { productId: 'prod_sports_003', productName: 'SwiftRun Pro Max', price: 5999, timestamp: '1 hour ago', source: 'DIRECT' }
        ],
        abandonedCarts: [],
        purchases: [
          { orderId: 'ord_sp_902', amount: 5999, items: ['SwiftRun Pro Max'], timestamp: '2026-08-29T17:00:00.000Z' }
        ]
      }
    },
    {
      id: 'cust_sports_105',
      merchantId: 'merchant_sports',
      name: 'Rohan Deshmukh',
      email: 'rohan.d@example.com',
      phone: '+91 99220 55190',
      location: 'Pune, MH',
      createdAt: '2026-08-15T09:00:00.000Z',
      lifetimeValue: 8400,
      status: 'lapsed',
      avatarColor: '#777777',
      currentIntent: 'DORMANT',
      nextBestAction: 'Dormant win-back incentive',
      metrics: {
        totalOrders: 1,
        totalSpend: 8400,
        averageOrderValue: 8400,
        lastPurchaseAt: '2026-08-15T09:30:00.000Z'
      },
      behavior: {
        viewedTimes: 1,
        lastViewedProduct: 'Hydration Flask 750ml',
        cartValue: 0,
        cartItems: [],
        daysActive: 14,
        hasPurchased: false,
        intentScore: 45,
        preferredCategories: ['Accessories'],
        viewedProducts: ['Hydration Flask 750ml'],
        searchQueries: ['Flask'],
        cartAdds: [],
        abandonedCarts: [],
        purchases: []
      }
    }
  ],

  merchant_fashion: [
    {
      id: 'cust_fash_201',
      merchantId: 'merchant_fashion',
      name: 'Priya Sharma',
      email: 'priya.sharma@example.com',
      phone: '+91 97112 00391',
      location: 'Mumbai, MH',
      createdAt: '2026-08-30T14:30:00.000Z',
      lifetimeValue: 28900,
      status: 'high_intent',
      avatarColor: '#111111',
      currentIntent: 'HIGH_RECOVERY_INTENT',
      nextBestAction: 'Dispatch Razorpay recovery payment link for ₹4,890 abandoned cart',
      metrics: {
        totalOrders: 0,
        totalSpend: 0,
        averageOrderValue: 0,
        lastPurchaseAt: null
      },
      behavior: {
        viewedTimes: 5,
        lastViewedProduct: 'Urban Performance Kurti & Stole Ensemble',
        cartValue: 4890,
        cartItems: ['Urban Performance Kurti & Stole Ensemble'],
        daysActive: 2,
        hasPurchased: false,
        intentScore: 94,
        abandonedAt: '18 mins ago',
        preferredCategories: ['Ethnic Wear', 'Kurtis', 'Ensembles'],
        viewedProducts: ['Urban Performance Kurti & Stole Ensemble'],
        searchQueries: ['I need a kurti under 5000'],
        cartAdds: [
          { productId: 'prod_fash_001', productName: 'Urban Performance Kurti & Stole Ensemble', price: 4890, timestamp: '18 mins ago', source: 'STOREFRONT' }
        ],
        abandonedCarts: [
          { items: ['Urban Performance Kurti & Stole Ensemble'], amount: 4890, timestamp: '18 mins ago' }
        ],
        purchases: []
      }
    },
    {
      id: 'cust_fash_202',
      merchantId: 'merchant_fashion',
      name: 'Sneha Roy',
      email: 'sneha.roy@example.com',
      phone: '+91 98301 99882',
      location: 'Kolkata, WB',
      createdAt: '2026-08-27T12:10:00.000Z',
      lifetimeValue: 19400,
      status: 'active',
      avatarColor: '#333333',
      currentIntent: 'HIGH_PURCHASE_INTENT',
      nextBestAction: 'Recommend matching accessories for floral dress',
      metrics: {
        totalOrders: 1,
        totalSpend: 999,
        averageOrderValue: 999,
        lastPurchaseAt: '2026-08-27T12:45:00.000Z'
      },
      behavior: {
        viewedTimes: 3,
        lastViewedProduct: 'Everyday Casual Floral Dress',
        cartValue: 999,
        cartItems: ['Everyday Casual Floral Dress'],
        daysActive: 1,
        hasPurchased: true,
        intentScore: 86,
        preferredCategories: ['Western Wear', 'Dresses'],
        viewedProducts: ['Everyday Casual Floral Dress'],
        searchQueries: ['Casual dresses'],
        cartAdds: [
          { productId: 'prod_fash_002', productName: 'Everyday Casual Floral Dress', price: 999, timestamp: '2 hours ago', source: 'AI_SEARCH' }
        ],
        abandonedCarts: [],
        purchases: [
          { orderId: 'ord_fa_101', amount: 999, items: ['Everyday Casual Floral Dress'], timestamp: '2026-08-27T12:45:00.000Z' }
        ]
      }
    },
    {
      id: 'cust_fash_203',
      merchantId: 'merchant_fashion',
      name: 'Meera Patel',
      email: 'meera.p@example.com',
      phone: '+91 98791 44552',
      location: 'Ahmedabad, GJ',
      createdAt: '2026-08-26T15:00:00.000Z',
      lifetimeValue: 38500,
      status: 'at_risk',
      avatarColor: '#555555',
      currentIntent: 'HIGH_RECOVERY_INTENT',
      nextBestAction: 'Recover abandoned Anarkali Kurta Set cart',
      metrics: {
        totalOrders: 0,
        totalSpend: 0,
        averageOrderValue: 0,
        lastPurchaseAt: null
      },
      behavior: {
        viewedTimes: 4,
        lastViewedProduct: 'Embroidered Anarkali Kurta Set',
        cartValue: 1899,
        cartItems: ['Embroidered Anarkali Kurta Set'],
        daysActive: 4,
        hasPurchased: false,
        intentScore: 90,
        abandonedAt: '45 mins ago',
        preferredCategories: ['Ethnic Wear', 'Festive'],
        viewedProducts: ['Embroidered Anarkali Kurta Set'],
        searchQueries: ['Anarkali set'],
        cartAdds: [
          { productId: 'prod_fash_003', productName: 'Embroidered Anarkali Kurta Set', price: 1899, timestamp: '45 mins ago', source: 'STOREFRONT' }
        ],
        abandonedCarts: [
          { items: ['Embroidered Anarkali Kurta Set'], amount: 1899, timestamp: '45 mins ago' }
        ],
        purchases: []
      }
    },
    {
      id: 'cust_fash_204',
      merchantId: 'merchant_fashion',
      name: 'Kavita Menon',
      email: 'kavita.m@example.com',
      phone: '+91 98401 22334',
      location: 'Chennai, TN',
      createdAt: '2026-08-10T10:00:00.000Z',
      lifetimeValue: 11200,
      status: 'lapsed',
      avatarColor: '#777777',
      currentIntent: 'DORMANT',
      nextBestAction: 'Dormant win-back incentive',
      metrics: {
        totalOrders: 0,
        totalSpend: 0,
        averageOrderValue: 0,
        lastPurchaseAt: null
      },
      behavior: {
        viewedTimes: 1,
        lastViewedProduct: 'Cotton Comfort Palazzo Pants',
        cartValue: 0,
        cartItems: [],
        daysActive: 21,
        hasPurchased: false,
        intentScore: 40,
        preferredCategories: ['Bottom Wear'],
        viewedProducts: ['Cotton Comfort Palazzo Pants'],
        searchQueries: ['Palazzo'],
        cartAdds: [],
        abandonedCarts: [],
        purchases: []
      }
    }
  ],

  merchant_tech: [
    {
      id: 'cust_tech_301',
      merchantId: 'merchant_tech',
      name: 'Rahul Verma',
      email: 'rahul.v@example.com',
      phone: '+91 98450 77123',
      location: 'Delhi NCR',
      createdAt: '2026-08-28T09:30:00.000Z',
      lifetimeValue: 9200,
      status: 'active',
      avatarColor: '#111111',
      currentIntent: 'HIGH_PURCHASE_INTENT',
      nextBestAction: 'Offer screen protector combo add-on',
      metrics: {
        totalOrders: 0,
        totalSpend: 0,
        averageOrderValue: 0,
        lastPurchaseAt: null
      },
      behavior: {
        viewedTimes: 3,
        lastViewedProduct: 'MagShield Kevlar Phone Case (iPhone 15 Pro)',
        cartValue: 1499,
        cartItems: ['MagShield Kevlar Phone Case (iPhone 15 Pro)'],
        daysActive: 2,
        hasPurchased: false,
        intentScore: 88,
        preferredCategories: ['Tech Accessories', 'Phone Cases'],
        viewedProducts: ['MagShield Kevlar Phone Case (iPhone 15 Pro)'],
        searchQueries: ['iPhone 15 case'],
        cartAdds: [
          { productId: 'prod_tech_001', productName: 'MagShield Kevlar Phone Case (iPhone 15 Pro)', price: 1499, timestamp: '30 mins ago', source: 'AI_SEARCH' }
        ],
        abandonedCarts: [],
        purchases: []
      }
    },
    {
      id: 'cust_tech_302',
      merchantId: 'merchant_tech',
      name: 'Arjun Singhania',
      email: 'arjun.s@example.com',
      phone: '+91 98200 11223',
      location: 'Mumbai, MH',
      createdAt: '2026-08-29T14:00:00.000Z',
      lifetimeValue: 42000,
      status: 'high_intent',
      avatarColor: '#333333',
      currentIntent: 'HIGH_RECOVERY_INTENT',
      nextBestAction: 'Trigger recovery link for Aluminum Laptop Stand',
      metrics: {
        totalOrders: 0,
        totalSpend: 0,
        averageOrderValue: 0,
        lastPurchaseAt: null
      },
      behavior: {
        viewedTimes: 5,
        lastViewedProduct: 'UltraSlim Ergonomic Aluminum Laptop Stand',
        cartValue: 3499,
        cartItems: ['UltraSlim Ergonomic Aluminum Laptop Stand'],
        daysActive: 3,
        hasPurchased: false,
        intentScore: 92,
        abandonedAt: '30 mins ago',
        preferredCategories: ['Workstation Accessories'],
        viewedProducts: ['UltraSlim Ergonomic Aluminum Laptop Stand'],
        searchQueries: ['Ergonomic laptop stand'],
        cartAdds: [
          { productId: 'prod_tech_002', productName: 'UltraSlim Ergonomic Aluminum Laptop Stand', price: 3499, timestamp: '30 mins ago', source: 'DIRECT' }
        ],
        abandonedCarts: [
          { items: ['UltraSlim Ergonomic Aluminum Laptop Stand'], amount: 3499, timestamp: '30 mins ago' }
        ],
        purchases: []
      }
    },
    {
      id: 'cust_tech_303',
      merchantId: 'merchant_tech',
      name: 'Neha Kapoor',
      email: 'neha.k@example.com',
      phone: '+91 98110 55667',
      location: 'Bengaluru, KA',
      createdAt: '2026-08-30T10:15:00.000Z',
      lifetimeValue: 24500,
      status: 'active',
      avatarColor: '#555555',
      currentIntent: 'HIGH_PURCHASE_INTENT',
      nextBestAction: 'Recommend braided 100W USB-C cable',
      metrics: {
        totalOrders: 1,
        totalSpend: 2199,
        averageOrderValue: 2199,
        lastPurchaseAt: '2026-08-30T10:45:00.000Z'
      },
      behavior: {
        viewedTimes: 4,
        lastViewedProduct: 'ProDesk Multi-Port USB-C Hub 7-in-1',
        cartValue: 2199,
        cartItems: ['ProDesk Multi-Port USB-C Hub 7-in-1'],
        daysActive: 1,
        hasPurchased: true,
        intentScore: 85,
        preferredCategories: ['Workstation Accessories'],
        viewedProducts: ['ProDesk Multi-Port USB-C Hub 7-in-1'],
        searchQueries: ['USB-C hub multi port'],
        cartAdds: [
          { productId: 'prod_tech_003', productName: 'ProDesk Multi-Port USB-C Hub 7-in-1', price: 2199, timestamp: '15 mins ago', source: 'AI_SEARCH' }
        ],
        abandonedCarts: [],
        purchases: [
          { orderId: 'ord_tc_301', amount: 2199, items: ['ProDesk Multi-Port USB-C Hub 7-in-1'], timestamp: '2026-08-30T10:45:00.000Z' }
        ]
      }
    }
  ]
};

export const INITIAL_MERCHANT_OPPORTUNITIES: Record<string, Opportunity[]> = {
  merchant_sports: [
    {
      id: 'opp_sports_101',
      merchantId: 'merchant_sports',
      type: 'cross_sell',
      title: 'Sports Socks Bundle Recommendation',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      customerBehavior: 'High Purchase Intent • Viewed Running Shoes 4×',
      productTarget: 'Velocity Runner X',
      aiRecommendation: 'Offer complementary Pro Dynamic Running Socks bundle (+₹799).',
      recommendedItem: {
        id: 'prod_socks_01',
        name: 'Pro Dynamic Running Socks (3-Pack)',
        price: 799,
        discountedPrice: 699
      },
      expectedRevenue: 1299,
      confidence: 94,
      opportunityScore: 94,
      status: 'ready',
      createdAt: '12 mins ago',
      createdByAgent: 'MERCHANDISING',
      reviewedByAgent: 'POLICY',
      executedByAgent: 'COMMERCE',
      reasoning: {
        observation: 'Customer visited Velocity Runner X 4 times in 36 hours and added item to cart.',
        signal: 'High purchase intent with hesitation at final cart step.',
        productRelationship: '78% of sports shoes buyers add anti-blister sports socks when offered as a 1-click bundle.',
        action: 'Recommend bundle with ₹100 instant bundle discount in Razorpay checkout.',
        expectedImpact: '₹1,299 expected net incremental basket value.',
        policyCheck: {
          passed: true,
          ruleName: 'AUTONOMOUS_EXECUTION_SAFE',
          details: 'Discount 10% <= 15% max limit. 0% margin dilution.',
          maxDiscountAllowed: 15,
          appliedDiscount: 10,
          requiresHumanApproval: false,
          riskScore: 'LOW'
        },
        toolUsed: 'CrossSellRecommendationEngine'
      }
    },
    {
      id: 'opp_sports_102',
      merchantId: 'merchant_sports',
      type: 'upsell',
      title: 'VIP Racing Footwear Upsell',
      customerId: 'cust_sports_103',
      customerName: 'Ananya Iyer',
      customerBehavior: 'High Intent • Viewed Marathon Shoe 6×',
      productTarget: 'SwiftRun Pro Max',
      aiRecommendation: 'Suggest AeroFlex Marathon Ultra with full carbon plate (+₹1,499).',
      expectedRevenue: 1499,
      confidence: 92,
      opportunityScore: 92,
      status: 'ready',
      createdAt: '1 hour ago',
      createdByAgent: 'MERCHANDISING',
      reviewedByAgent: 'POLICY',
      executedByAgent: 'COMMERCE',
      reasoning: {
        observation: 'Customer logged 18+ minutes reading technical specs of marathon carbon plate models.',
        signal: 'Performance runner seeking maximum energy return.',
        productRelationship: 'AeroFlex Marathon Ultra delivers 3.4x higher energy return.',
        action: 'Trigger in-app spec comparison highlighting carbon propulsion.',
        expectedImpact: '₹1,499 incremental transaction value.',
        policyCheck: {
          passed: true,
          ruleName: 'AUTONOMOUS_EXECUTION_SAFE',
          details: 'Within autonomous price delta tolerance.',
          maxDiscountAllowed: 15,
          appliedDiscount: 8,
          requiresHumanApproval: false,
          riskScore: 'LOW'
        },
        toolUsed: 'CatalogUpsellEngine'
      }
    },
    {
      id: 'opp_sports_103',
      merchantId: 'merchant_sports',
      type: 'cross_sell',
      title: 'Running Cap Post-Purchase Cross-Sell',
      customerId: 'cust_sports_104',
      customerName: 'Vikram Sengupta',
      customerBehavior: 'Active • Completed SwiftRun purchase',
      productTarget: 'SwiftRun Pro Max',
      aiRecommendation: 'Suggest Breathable Running Cap (+₹699).',
      recommendedItem: {
        id: 'prod_cap_01',
        name: 'Breathable Running Cap',
        price: 699
      },
      expectedRevenue: 699,
      confidence: 88,
      opportunityScore: 88,
      status: 'ready',
      createdAt: '2 hours ago',
      createdByAgent: 'MERCHANDISING',
      reviewedByAgent: 'POLICY',
      executedByAgent: 'COMMERCE',
      reasoning: {
        observation: 'Customer completed footwear purchase. High affinity for sun protection accessories.',
        signal: 'Outdoor running persona.',
        productRelationship: '65% of shoe buyers buy a cap within 30 days.',
        action: 'Dispatch 1-click test checkout link.',
        expectedImpact: '₹699 basket expansion.',
        policyCheck: {
          passed: true,
          ruleName: 'AUTONOMOUS_EXECUTION_SAFE',
          details: 'Passed policy rules.',
          maxDiscountAllowed: 15,
          appliedDiscount: 0,
          requiresHumanApproval: false,
          riskScore: 'LOW'
        },
        toolUsed: 'AffinityRecommender'
      }
    }
  ],

  merchant_fashion: [
    {
      id: 'opp_fash_201',
      merchantId: 'merchant_fashion',
      type: 'checkout_recovery',
      title: '₹4,890 Abandoned Cart Recovery',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      customerBehavior: 'Priya added products to cart but abandoned checkout before payment.',
      productTarget: 'Urban Performance Kurti & Stole Ensemble',
      aiRecommendation: 'Generate a Razorpay Test Mode recovery payment link for ₹4,890.',
      expectedRevenue: 4890,
      confidence: 94,
      opportunityScore: 94,
      status: 'awaiting_approval',
      createdAt: '18 mins ago',
      createdByAgent: 'RECOVERY',
      reviewedByAgent: 'POLICY',
      executedByAgent: 'COMMERCE',
      reasoning: {
        observation: 'Priya added products to cart (₹4,890) but abandoned checkout before payment.',
        signal: 'Detected checkout abandonment — cart ₹4,890, payment not completed. Classified as HIGH_RECOVERY_INTENT.',
        productRelationship: 'Customer showed purchase intent but exited before payment.',
        action: 'Generate a Razorpay Test Mode recovery payment link for ₹4,890.',
        expectedImpact: '₹4,890 recovered revenue.',
        policyCheck: {
          passed: true,
          ruleName: 'RECOVERY_LIMIT_SAFE',
          details: 'Recovery payment link is within allowed limits. POLICY: ALLOWED · RESULT: APPROVED. Merchant approval required before commerce execution.',
          maxDiscountAllowed: 20,
          appliedDiscount: 0,
          requiresHumanApproval: true,
          riskScore: 'LOW'
        },
        toolUsed: 'RazorpaySmartLinkGenerator'
      }
    },
    {
      id: 'opp_fash_202',
      merchantId: 'merchant_fashion',
      type: 'checkout_recovery',
      title: 'Festive Anarkali Cart Recovery',
      customerId: 'cust_fash_203',
      customerName: 'Meera Patel',
      customerBehavior: 'Cart drop-off on Anarkali Kurta Set (₹1,899)',
      productTarget: 'Embroidered Anarkali Kurta Set',
      aiRecommendation: 'Send personalized 1-click Razorpay Test Payment link with ₹150 festive credit.',
      expectedRevenue: 1899,
      confidence: 90,
      opportunityScore: 90,
      status: 'awaiting_approval',
      createdAt: '30 mins ago',
      createdByAgent: 'RECOVERY',
      reviewedByAgent: 'POLICY',
      executedByAgent: 'COMMERCE',
      reasoning: {
        observation: 'High value cart ₹1,899 dropped at payment method selection.',
        signal: 'Price hesitation on premium ethnic set.',
        productRelationship: 'High margin item (44% gross margin).',
        action: 'Dispatch smart payment link with ₹150 instant checkout incentive.',
        expectedImpact: '₹1,899 recovered revenue.',
        policyCheck: {
          passed: true,
          ruleName: 'HUMAN_APPROVAL_GATE',
          details: 'Order value within FashionHub policy limits. Approval requested.',
          maxDiscountAllowed: 20,
          appliedDiscount: 8,
          requiresHumanApproval: true,
          riskScore: 'LOW'
        },
        toolUsed: 'CartRecoveryAgent'
      }
    }
  ],

  merchant_tech: [
    {
      id: 'opp_tech_301',
      merchantId: 'merchant_tech',
      type: 'cross_sell',
      title: '9H Screen Protector Cross-Sell',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      customerBehavior: 'Purchasing MagShield Kevlar Phone Case',
      productTarget: 'MagShield Kevlar Phone Case (iPhone 15 Pro)',
      aiRecommendation: 'Recommend 9H DiamondEdge Screen Protector (+₹799).',
      recommendedItem: {
        id: 'prod_screen_01',
        name: '9H DiamondEdge Screen Protector',
        price: 799
      },
      expectedRevenue: 799,
      confidence: 88,
      opportunityScore: 88,
      status: 'ready',
      createdAt: '20 mins ago',
      createdByAgent: 'MERCHANDISING',
      reviewedByAgent: 'POLICY',
      executedByAgent: 'COMMERCE',
      reasoning: {
        observation: 'Customer has iPhone 15 Pro Kevlar case in cart.',
        signal: 'Device protection affinity.',
        productRelationship: '92% co-purchase rate between cases and tempered glass shields.',
        action: 'Present pre-checked add-on item in Razorpay Smart Cart.',
        expectedImpact: '₹799 instant basket expansion.',
        policyCheck: {
          passed: true,
          ruleName: 'AUTONOMOUS_EXECUTION_SAFE',
          details: 'TechNest policy ceiling (10%) respected. 0% discount required.',
          maxDiscountAllowed: 10,
          appliedDiscount: 0,
          requiresHumanApproval: false,
          riskScore: 'LOW'
        },
        toolUsed: 'TechAffinityRecommender'
      }
    },
    {
      id: 'opp_tech_302',
      merchantId: 'merchant_tech',
      type: 'checkout_recovery',
      title: 'Ergonomic Laptop Stand Cart Recovery',
      customerId: 'cust_tech_302',
      customerName: 'Arjun Singhania',
      customerBehavior: 'Abandoned cart valued at ₹3,499',
      productTarget: 'UltraSlim Ergonomic Aluminum Laptop Stand',
      aiRecommendation: 'Dispatch 1-click Razorpay test recovery link with posture setup guide.',
      expectedRevenue: 3499,
      confidence: 92,
      opportunityScore: 92,
      status: 'awaiting_approval',
      createdAt: '35 mins ago',
      createdByAgent: 'RECOVERY',
      reviewedByAgent: 'POLICY',
      executedByAgent: 'COMMERCE',
      reasoning: {
        observation: 'Customer spent 12 mins comparing aluminum stands before dropping at checkout.',
        signal: 'High consideration workstation buyer.',
        productRelationship: 'High margin inventory.',
        action: 'Send instant recovery link.',
        expectedImpact: '₹3,499 recovered revenue.',
        policyCheck: {
          passed: true,
          ruleName: 'HUMAN_APPROVAL_GATE',
          details: 'Requires 1-click merchant signoff.',
          maxDiscountAllowed: 10,
          appliedDiscount: 5,
          requiresHumanApproval: true,
          riskScore: 'LOW'
        },
        toolUsed: 'CartRecoveryAgent'
      }
    }
  ]
};

export const INITIAL_MERCHANT_TRANSACTIONS: Record<string, Transaction[]> = {
  merchant_sports: [
    {
      id: 'TX_SP_201',
      merchantId: 'merchant_sports',
      razorpayPaymentId: 'pay_test_sports_9921L',
      razorpayOrderId: 'order_test_sports_8819L',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      baseProduct: 'Velocity Runner X',
      baseAmount: 6999,
      aiAddonProduct: 'Pro Dynamic Running Socks (3-Pack)',
      aiAddonAmount: 799,
      totalAmount: 7798,
      aiAttribution: 'AI Cross-sell',
      aiAttributedRevenue: 799,
      status: 'SUCCESS',
      timestamp: '2026-09-04 14:30:00',
      paymentMethod: 'UPI'
    },
    {
      id: 'TX_SP_202',
      merchantId: 'merchant_sports',
      razorpayPaymentId: 'pay_test_sports_7701P',
      razorpayOrderId: 'order_test_sports_6602P',
      customerId: 'cust_sports_103',
      customerName: 'Ananya Iyer',
      baseProduct: 'AeroFlex Marathon Ultra',
      baseAmount: 8499,
      totalAmount: 8499,
      aiAttribution: 'Direct',
      aiAttributedRevenue: 0,
      status: 'SUCCESS',
      timestamp: '2026-09-04 12:15:20',
      paymentMethod: 'Netbanking'
    }
  ],

  merchant_fashion: [
    {
      id: 'TX_FA_301',
      merchantId: 'merchant_fashion',
      razorpayPaymentId: 'pay_test_fash_4481M',
      razorpayOrderId: 'order_test_fash_3370M',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      baseProduct: 'Urban Performance Kurti',
      baseAmount: 899,
      aiAddonProduct: 'Chiffon Matching Dupatta',
      aiAddonAmount: 499,
      totalAmount: 1398,
      aiAttribution: 'AI Cross-sell',
      aiAttributedRevenue: 499,
      status: 'SUCCESS',
      timestamp: '2026-09-04 15:45:10',
      paymentMethod: 'UPI'
    },
    {
      id: 'TX_FA_302',
      merchantId: 'merchant_fashion',
      razorpayPaymentId: 'pay_test_fash_5592K',
      razorpayOrderId: 'order_test_fash_4481K',
      customerId: 'cust_fash_202',
      customerName: 'Sneha Roy',
      baseProduct: 'Everyday Casual Floral Dress',
      baseAmount: 999,
      totalAmount: 999,
      aiAttribution: 'Direct',
      aiAttributedRevenue: 0,
      status: 'SUCCESS',
      timestamp: '2026-09-04 11:20:00',
      paymentMethod: 'Card'
    }
  ],

  merchant_tech: [
    {
      id: 'TX_TE_401',
      merchantId: 'merchant_tech',
      razorpayPaymentId: 'pay_test_tech_8819R',
      razorpayOrderId: 'order_test_tech_7708R',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      baseProduct: 'MagShield Kevlar Phone Case (iPhone 15 Pro)',
      baseAmount: 1499,
      aiAddonProduct: '9H DiamondEdge Screen Protector',
      aiAddonAmount: 799,
      totalAmount: 2298,
      aiAttribution: 'AI Cross-sell',
      aiAttributedRevenue: 799,
      status: 'SUCCESS',
      timestamp: '2026-09-04 16:10:00',
      paymentMethod: 'UPI'
    },
    {
      id: 'TX_TE_402',
      merchantId: 'merchant_tech',
      razorpayPaymentId: 'pay_test_tech_9920S',
      razorpayOrderId: 'order_test_tech_8819S',
      customerId: 'cust_tech_303',
      customerName: 'Neha Kapoor',
      baseProduct: 'ProDesk Multi-Port USB-C Hub 7-in-1',
      baseAmount: 2199,
      totalAmount: 2199,
      aiAttribution: 'Direct',
      aiAttributedRevenue: 0,
      status: 'SUCCESS',
      timestamp: '2026-09-04 13:05:00',
      paymentMethod: 'Card'
    }
  ]
};

export const INITIAL_MERCHANT_ACTIVITY: Record<string, AgentActivityItem[]> = {
  merchant_sports: [
    {
      id: 'act_sp_1',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:30:00Z',
      timeFormatted: '14:30',
      stage: 'RESULT',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      title: 'Captured ₹7,798 in Razorpay Test Mode',
      description: 'Captured ₹799 AI cross-sell uplift on Velocity Runner X + Pro Socks.',
      toolUsed: 'RazorpayPaymentCapture',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_sp_2',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:28:00Z',
      timeFormatted: '14:28',
      stage: 'ACTION',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      title: 'Commerce Agent generated 1-click test checkout',
      description: 'Dispatched dynamic bundle prompt for UrbanKart catalog.',
      toolUsed: 'RazorpayOrderAPI',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_sp_3',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:27:00Z',
      timeFormatted: '14:27',
      stage: 'APPROVAL',
      agent: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      title: 'Merchant approved recommendation',
      description: 'Merchant approved sports socks bundle recommendation (+₹799 uplift).',
      toolUsed: 'MerchantApprovalGateway',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_sp_4',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:26:30Z',
      timeFormatted: '14:26',
      stage: 'POLICY',
      agent: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      title: 'Policy Agent approved 10% discount within 15% merchant limit',
      description: 'Evaluated bundle discount; passed margin protection safeguard.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_sp_5',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:26:00Z',
      timeFormatted: '14:26',
      stage: 'RECOMMEND',
      agent: 'MERCHANDISING',
      agentName: 'Merchandising Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      title: 'Merchandising Agent recommended Pro Dynamic Running Socks',
      description: 'Matched Pro Dynamic Running Socks (+₹799) from UrbanKart catalog.',
      toolUsed: 'AffinityGraphRecommender',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_sp_6',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:25:30Z',
      timeFormatted: '14:25',
      stage: 'UNDERSTAND',
      agent: 'INTENT',
      agentName: 'Customer Intent Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      title: 'Intent Agent classified Aarav Mehta as high purchase intent',
      description: 'Evaluated 4 repeat visits on Velocity Runner X + cart addition (94% confidence).',
      toolUsed: 'IntentClassifier_v2',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_sp_7',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:25:00Z',
      timeFormatted: '14:25',
      stage: 'OBSERVE',
      agent: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      title: 'Supervisor routed customer signal to Intent Agent',
      description: 'Ingested live session telemetry for Aarav Mehta.',
      toolUsed: 'TaskRouter',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_sp_8',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T13:15:00Z',
      timeFormatted: '13:15',
      stage: 'POLICY',
      agent: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_sports_104',
      customerName: 'Rohan Gupta',
      title: 'Policy Agent blocked action: discount exceeded 15% limit',
      description: 'Blocked 25% promotional coupon request exceeding UrbanKart 15% limit.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'BLOCKED',
      status: 'warning'
    }
  ],

  merchant_fashion: [
    {
      id: 'act_fa_1',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:45:10Z',
      timeFormatted: '15:45',
      stage: 'RESULT',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      title: 'Captured ₹1,398 in Razorpay Test Mode',
      description: 'Captured ₹499 AI cross-sell uplift on Urban Performance Kurti + Dupatta.',
      toolUsed: 'RazorpayPaymentCapture',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_fa_2',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:44:00Z',
      timeFormatted: '15:44',
      stage: 'ACTION',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      title: 'Commerce Agent generated 1-click test checkout',
      description: 'Dispatched dynamic 1-click bundle link for FashionHub lookbook.',
      toolUsed: 'RazorpayOrderAPI',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_fa_3',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:43:30Z',
      timeFormatted: '15:43',
      stage: 'POLICY',
      agent: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      title: 'Policy Agent approved 15% discount within 20% merchant limit',
      description: 'Verified festive styling package under FashionHub margin limits.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_fa_4',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:43:00Z',
      timeFormatted: '15:43',
      stage: 'RECOMMEND',
      agent: 'MERCHANDISING',
      agentName: 'Merchandising Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      title: 'Merchandising Agent recommended Dupatta bundle',
      description: 'Matched Chiffon Matching Dupatta (+₹499) from FashionHub catalog.',
      toolUsed: 'LookbookBundleEngine',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_fa_5',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:41:00Z',
      timeFormatted: '15:41',
      stage: 'RECOMMEND',
      agent: 'RECOVERY',
      agentName: 'Revenue Recovery Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      title: 'Recovery Agent generated checkout recovery recommendation',
      description: 'Synthesized 1-click smart recovery incentive for abandoned cart.',
      toolUsed: 'CheckoutRecoveryEngine',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_fa_6',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:40:00Z',
      timeFormatted: '15:40',
      stage: 'UNDERSTAND',
      agent: 'INTENT',
      agentName: 'Customer Intent Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      title: 'Intent Agent classified Priya Sharma as high purchase intent',
      description: 'Evaluated 5 session page loads on Urban Performance Kurti (94% confidence).',
      toolUsed: 'IntentClassifier_v2',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_fa_7',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:39:00Z',
      timeFormatted: '15:39',
      stage: 'OBSERVE',
      agent: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      title: 'Supervisor routed customer signal to Intent Agent',
      description: 'Ingested kurti lookbook browsing event for Priya Sharma.',
      toolUsed: 'TaskRouter',
      policyStatus: 'ALLOWED',
      status: 'info'
    }
  ],

  merchant_tech: [
    {
      id: 'act_te_1',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:10:00Z',
      timeFormatted: '16:10',
      stage: 'RESULT',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      title: 'Captured ₹2,298 in Razorpay Test Mode',
      description: 'Captured ₹799 AI cross-sell uplift on MagShield Case + 9H Screen Protector.',
      toolUsed: 'RazorpayPaymentCapture',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_te_2',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:09:00Z',
      timeFormatted: '16:09',
      stage: 'ACTION',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      title: 'Commerce Agent generated 1-click test checkout',
      description: 'Dispatched dynamic 1-click order for TechNest accessory pairing.',
      toolUsed: 'RazorpayOrderAPI',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_te_3',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:08:00Z',
      timeFormatted: '16:08',
      stage: 'POLICY',
      agent: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      title: 'Policy Agent approved 10% discount within 10% merchant limit',
      description: 'Passed TechNest 10% discount ceiling and margin floor check.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'ALLOWED',
      status: 'success'
    },
    {
      id: 'act_te_4',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:07:00Z',
      timeFormatted: '16:07',
      stage: 'RECOMMEND',
      agent: 'MERCHANDISING',
      agentName: 'Merchandising Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      title: 'Merchandising Agent recommended 9H DiamondEdge Screen Protector',
      description: 'Matched 9H DiamondEdge Screen Protector (+₹799) from TechNest catalog.',
      toolUsed: 'ProductAffinityGraph',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_te_5',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:06:00Z',
      timeFormatted: '16:06',
      stage: 'UNDERSTAND',
      agent: 'INTENT',
      agentName: 'Customer Intent Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      title: 'Intent Agent classified Rahul Verma as high purchase intent',
      description: 'Diagnosed high purchase intent on MagShield Kevlar Case (88% confidence).',
      toolUsed: 'IntentClassifier_v2',
      policyStatus: 'ALLOWED',
      status: 'info'
    },
    {
      id: 'act_te_6',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:05:00Z',
      timeFormatted: '16:05',
      stage: 'OBSERVE',
      agent: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      title: 'Supervisor routed customer signal to Intent Agent',
      description: 'Ingested workstation accessory browsing telemetry for Rahul Verma.',
      toolUsed: 'TaskRouter',
      policyStatus: 'ALLOWED',
      status: 'info'
    }
  ]
};

export const INITIAL_MERCHANT_AUDIT: Record<string, AuditLog[]> = {
  merchant_sports: [
    {
      id: 'aud_sp_1',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:30:00.102Z',
      event: 'RESULT',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      agentDecision: 'Captured ₹7,798 in Razorpay Test Mode — ₹799 AI cross-sell uplift on Velocity Runner X + Pro Socks.',
      toolUsed: 'RazorpayPaymentCapture',
      policyStatus: 'ALLOWED',
      policyDetails: 'Verified against UrbanKart policy limits (max 15% discount). Payment ID: pay_test_9921Ka9124L.',
      result: 'SUCCESS',
      signatureHash: '0x8f2a99e1c3b77209'
    },
    {
      id: 'aud_sp_2',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:28:00.312Z',
      event: 'ACTION',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      agentDecision: 'Commerce Agent generated 1-click test checkout — Dispatched dynamic bundle prompt for UrbanKart catalog.',
      toolUsed: 'RazorpayOrderAPI',
      policyStatus: 'ALLOWED',
      policyDetails: 'Order created: order_test_881920KaL in Razorpay Test Sandbox.',
      result: 'SUCCESS',
      signatureHash: '0x10b77e8ca49233dc'
    },
    {
      id: 'aud_sp_3',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:27:00.540Z',
      event: 'APPROVAL',
      agent: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      agentDecision: 'Merchant approved recommendation — Sports Socks Bundle (+₹799 uplift) approved for checkout.',
      toolUsed: 'MerchantApprovalGateway',
      policyStatus: 'ALLOWED',
      policyDetails: 'Merchant sign-off recorded. Guardrails intact.',
      result: 'EXECUTED',
      signatureHash: '0x22c98ff0901ab764'
    },
    {
      id: 'aud_sp_4',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:26:30.820Z',
      event: 'POLICY',
      agent: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      agentDecision: 'Policy Agent approved 10% discount within 15% merchant limit — Margin safeguard passed.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'ALLOWED',
      policyDetails: 'Evaluated discount 10% against UrbanKart 15% maximum discount ceiling.',
      result: 'SUCCESS',
      signatureHash: '0x99a0cb4112e7fe32'
    },
    {
      id: 'aud_sp_5',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:26:00.040Z',
      event: 'RECOMMEND',
      agent: 'MERCHANDISING',
      agentName: 'Merchandising Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      agentDecision: 'Merchandising Agent recommended Pro Dynamic Running Socks — Matched Pro Dynamic Running Socks (+₹799) from UrbanKart catalog.',
      toolUsed: 'AffinityGraphRecommender',
      policyStatus: 'ALLOWED',
      policyDetails: '94% co-purchase affinity with Velocity Runner X.',
      result: 'SUCCESS',
      signatureHash: '0x5e19cc442b08a117'
    },
    {
      id: 'aud_sp_6',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:25:30.120Z',
      event: 'UNDERSTAND',
      agent: 'INTENT',
      agentName: 'Customer Intent Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      agentDecision: 'Intent Agent classified Aarav Mehta as high purchase intent — 4 repeat visits on Velocity Runner X + cart addition.',
      toolUsed: 'IntentClassifier_v2',
      policyStatus: 'ALLOWED',
      policyDetails: 'Intent score 94/100. Signal verified from real-time session telemetry.',
      result: 'SUCCESS',
      signatureHash: '0x7c41b8a901ff2148'
    },
    {
      id: 'aud_sp_7',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T14:25:00.010Z',
      event: 'OBSERVE',
      agent: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_sports_102',
      customerName: 'Aarav Mehta',
      agentDecision: 'Supervisor routed customer signal to Intent Agent — Ingested cart telemetry for Aarav Mehta.',
      toolUsed: 'TaskRouter',
      policyStatus: 'ALLOWED',
      policyDetails: 'Routing policy satisfied: active customer session with high signal priority.',
      result: 'SUCCESS',
      signatureHash: '0x34d081f9a672bb19'
    },
    {
      id: 'aud_sp_8',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T13:15:00.000Z',
      event: 'POLICY',
      agent: 'POLICY',
      agentId: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_sports_104',
      customerName: 'Rohan Gupta',
      agentDecision: 'Policy Agent blocked action: discount exceeded 15% limit — Requested 25% promotional coupon blocked.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'BLOCKED',
      policyDetails: 'Strict margin protection enforced. Max allowed is 15%.',
      result: 'BLOCKED',
      signatureHash: '0x6a11fe88b209d731'
    },
    {
      id: 'aud_sp_9',
      merchantId: 'merchant_sports',
      timestamp: '2026-09-04T12:45:00.000Z',
      event: 'RECOMMEND',
      agent: 'RECOVERY',
      agentId: 'RECOVERY',
      agentName: 'Revenue Recovery Agent',
      customerId: 'cust_sports_105',
      customerName: 'Rohan Deshmukh',
      agentDecision: 'Recovery Agent recommended a Razorpay recovery payment link for ₹2,499 — Generated 1-click test recovery link for lapsed session.',
      toolUsed: 'RazorpaySmartLinkGenerator',
      policyStatus: 'ALLOWED',
      policyDetails: 'Recovery action validated within UrbanKart merchant policy limits.',
      result: 'SUCCESS',
      signatureHash: '0x9920aa44bb331102'
    }
  ],

  merchant_fashion: [
    {
      id: 'aud_fa_1',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:45:10.420Z',
      event: 'RESULT',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      agentDecision: 'Captured ₹1,398 in Razorpay Test Mode — ₹499 AI cross-sell uplift on Urban Performance Kurti + Dupatta.',
      toolUsed: 'RazorpayPaymentCapture',
      policyStatus: 'ALLOWED',
      policyDetails: 'Verified against FashionHub policy limits (max 20% discount).',
      result: 'SUCCESS',
      signatureHash: '0x7c41b8a901ff2148'
    },
    {
      id: 'aud_fa_2',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:44:00.210Z',
      event: 'ACTION',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      agentDecision: 'Commerce Agent generated 1-click test checkout — Dispatched dynamic 1-click bundle link for FashionHub lookbook.',
      toolUsed: 'RazorpayOrderAPI',
      policyStatus: 'ALLOWED',
      policyDetails: 'Order created in Razorpay Test Sandbox under FashionHub key.',
      result: 'SUCCESS',
      signatureHash: '0x88f12a9b33c091ad'
    },
    {
      id: 'aud_fa_3',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:43:30.150Z',
      event: 'POLICY',
      agent: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      agentDecision: 'Policy Agent approved 15% discount within 20% merchant limit — Margin safeguard passed.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'ALLOWED',
      policyDetails: 'Discount 15% <= FashionHub 20% ceiling.',
      result: 'SUCCESS',
      signatureHash: '0x334bc89901aa4411'
    },
    {
      id: 'aud_fa_4',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:43:00.080Z',
      event: 'RECOMMEND',
      agent: 'MERCHANDISING',
      agentName: 'Merchandising Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      agentDecision: 'Merchandising Agent recommended Dupatta bundle — Matched Chiffon Matching Dupatta (+₹499) from FashionHub catalog.',
      toolUsed: 'LookbookBundleEngine',
      policyStatus: 'ALLOWED',
      policyDetails: 'High category affinity with festive kurti collection.',
      result: 'SUCCESS',
      signatureHash: '0x5511ba900ff12499'
    },
    {
      id: 'aud_fa_5',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:41:00.000Z',
      event: 'RECOMMEND',
      agent: 'RECOVERY',
      agentName: 'Revenue Recovery Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      agentDecision: 'Recovery Agent generated checkout recovery recommendation — Synthesized 1-click smart recovery incentive for abandoned cart.',
      toolUsed: 'CheckoutRecoveryEngine',
      policyStatus: 'ALLOWED',
      policyDetails: 'Cart abandoned 24 mins ago. Recovery probability 89%.',
      result: 'SUCCESS',
      signatureHash: '0x9920aa44bb331102'
    },
    {
      id: 'aud_fa_6',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:40:00.020Z',
      event: 'UNDERSTAND',
      agent: 'INTENT',
      agentName: 'Customer Intent Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      agentDecision: 'Intent Agent classified Priya Sharma as high purchase intent — Evaluated 5 session page loads on Urban Performance Kurti (94% confidence).',
      toolUsed: 'IntentClassifier_v2',
      policyStatus: 'ALLOWED',
      policyDetails: 'Deep browsing and repeated color swatch reviews.',
      result: 'SUCCESS',
      signatureHash: '0x12a9bc884400fe32'
    },
    {
      id: 'aud_fa_7',
      merchantId: 'merchant_fashion',
      timestamp: '2026-09-04T15:39:00.010Z',
      event: 'OBSERVE',
      agent: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_fash_201',
      customerName: 'Priya Sharma',
      agentDecision: 'Supervisor routed customer signal to Intent Agent — Ingested kurti lookbook browsing event for Priya Sharma.',
      toolUsed: 'TaskRouter',
      policyStatus: 'ALLOWED',
      policyDetails: 'Task routing initialized for FashionHub studio traffic.',
      result: 'SUCCESS',
      signatureHash: '0x447788110099bbcc'
    }
  ],

  merchant_tech: [
    {
      id: 'aud_te_1',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:10:00.089Z',
      event: 'RESULT',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      agentDecision: 'Captured ₹2,298 in Razorpay Test Mode — ₹799 AI cross-sell uplift on MagShield Case + 9H Screen Protector.',
      toolUsed: 'RazorpayPaymentCapture',
      policyStatus: 'ALLOWED',
      policyDetails: 'Verified against TechNest policy limits (max 10% discount).',
      result: 'SUCCESS',
      signatureHash: '0x5e19cc442b08a117'
    },
    {
      id: 'aud_te_2',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:09:00.050Z',
      event: 'ACTION',
      agent: 'COMMERCE',
      agentName: 'Commerce Execution Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      agentDecision: 'Commerce Agent generated 1-click test checkout — Dispatched dynamic 1-click order for TechNest accessory pairing.',
      toolUsed: 'RazorpayOrderAPI',
      policyStatus: 'ALLOWED',
      policyDetails: 'Order created in Razorpay Test Sandbox under TechNest key.',
      result: 'SUCCESS',
      signatureHash: '0x77bb110099aa4422'
    },
    {
      id: 'aud_te_3',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:08:00.020Z',
      event: 'POLICY',
      agent: 'POLICY',
      agentName: 'Policy & Risk Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      agentDecision: 'Policy Agent approved 10% discount within 10% merchant limit — Passed TechNest 10% discount ceiling and margin floor check.',
      toolUsed: 'PolicyGuard',
      policyStatus: 'ALLOWED',
      policyDetails: 'Margin compliance verified on hardware accessory cluster.',
      result: 'SUCCESS',
      signatureHash: '0x9922cc110088ffaa'
    },
    {
      id: 'aud_te_4',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:07:00.010Z',
      event: 'RECOMMEND',
      agent: 'MERCHANDISING',
      agentName: 'Merchandising Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      agentDecision: 'Merchandising Agent recommended 9H DiamondEdge Screen Protector — Matched 9H DiamondEdge Screen Protector (+₹799) from TechNest catalog.',
      toolUsed: 'ProductAffinityGraph',
      policyStatus: 'ALLOWED',
      policyDetails: '92% device compatibility pairing affinity.',
      result: 'SUCCESS',
      signatureHash: '0x1100334455667788'
    },
    {
      id: 'aud_te_5',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:06:00.000Z',
      event: 'UNDERSTAND',
      agent: 'INTENT',
      agentName: 'Customer Intent Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      agentDecision: 'Intent Agent classified Rahul Verma as high purchase intent — Diagnosed high purchase intent on MagShield Kevlar Case (88% confidence).',
      toolUsed: 'IntentClassifier_v2',
      policyStatus: 'ALLOWED',
      policyDetails: 'Device model detection matched iPhone 15 Pro accessory.',
      result: 'SUCCESS',
      signatureHash: '0x9988776655443322'
    },
    {
      id: 'aud_te_6',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T16:05:00.000Z',
      event: 'OBSERVE',
      agent: 'SUPERVISOR',
      agentId: 'SUPERVISOR',
      agentName: 'Growth Supervisor Agent',
      customerId: 'cust_tech_301',
      customerName: 'Rahul Verma',
      agentDecision: 'Supervisor routed customer signal to Intent Agent — Ingested workstation accessory browsing telemetry for Rahul Verma.',
      toolUsed: 'TaskRouter',
      policyStatus: 'ALLOWED',
      policyDetails: 'Ingested session start signal for TechNest store.',
      result: 'SUCCESS',
      signatureHash: '0x1234567890abcdef'
    },
    {
      id: 'aud_te_7',
      merchantId: 'merchant_tech',
      timestamp: '2026-09-04T15:30:00.000Z',
      event: 'RECOMMEND',
      agent: 'RECOVERY',
      agentId: 'RECOVERY',
      agentName: 'Revenue Recovery Agent',
      customerId: 'cust_tech_302',
      customerName: 'Arjun Singhania',
      agentDecision: 'Recovery Agent recommended a Razorpay recovery payment link for ₹3,499 — Generated 1-click test recovery link for abandoned workstation cart.',
      toolUsed: 'RazorpaySmartLinkGenerator',
      policyStatus: 'ALLOWED',
      policyDetails: 'Recovery action validated within TechNest merchant policy limits.',
      result: 'SUCCESS',
      signatureHash: '0x3344aaccbb110099'
    }
  ]
};
